# Generated by Django 2.2.11 on 2020-04-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0004_auto_20200407_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dgf.Division'),
        ),
    ]
