# Generated by Django 2.2.11 on 2020-04-23 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0011_auto_20200423_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('P', 'Practice'), ('C', 'Casual Round'), ('T', 'Tournament')],
                                          max_length=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dgf.Course')),
                ('disc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dgf.Disc')),
                ('friend',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aces', to='dgf.Friend')),
            ],
        ),
    ]
