# Generated by Django 2.2.11 on 2020-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='sponsor_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
