# Generated by Django 2.2.11 on 2020-04-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0015_disc_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dgf.Friend'),
        ),
    ]
