# Generated by Django 2.2.11 on 2020-04-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0018_ace_partial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights',
                                    to='dgf.Friend'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'In the bag'), ('A', 'Ace'), ('O', 'Other')], default='O',
                                          max_length=1)),
                ('url', models.URLField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos',
                                             to='dgf.Friend')),
            ],
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('url', 'friend'), name='unique_video_for_friend'),
        ),
    ]
