# Generated by Django 2.2.13 on 2020-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0022_auto_20200505_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='best_score_in_wischlingen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Best score in Wischlingen'),
        ),
    ]
