# Generated by Django 2.2.13 on 2020-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0023_friend_best_score_in_wischlingen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='friend',
            name='best_score_in_wischlingen',
            field=models.IntegerField(blank=True, null=True,
                                      verbose_name='Best score in Wischlingen (relative to par)'),
        ),
    ]
