# Generated by Django 2.2.13 on 2020-06-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0024_auto_20200615_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='place',
        ),
    ]
