# Generated by Django 2.2.13 on 2020-06-27 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0024_auto_20200615_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discinbag',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='Amount'),
        ),
    ]
