# Generated by Django 2.2.17 on 2020-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0026_auto_20200629_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other hobbies'),
        ),
        migrations.AddField(
            model_name='friend',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Job"),
        ),
    ]
