# Generated by Django 2.2.17 on 2021-03-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0028_friend_udisc_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dgf_coursepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Course')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
