# Generated by Django 2.2.17 on 2021-03-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0030_course_udisc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdiscRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Last score from UDisc')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Course')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Friend')),
            ],
        ),
    ]
