# Generated by Django 2.2.17 on 2021-03-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0030_course_udisc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdiscRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Last score from UDisc')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Course')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Friend')),
            ],
        ),
        migrations.AddConstraint(
            model_name='udiscround',
            constraint=models.UniqueConstraint(fields=('course', 'friend'),
                                               name='Only one score per course and friend allowed. The best one'),
        ),
    ]
