# Generated by Django 2.2.17 on 2021-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0031_udiscround'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='udisc_main_layout',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Layout'),
        ),
    ]
