# Generated by Django 2.2.17 on 2021-03-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0033_friend_gt_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('pdga_number',), name='unique_pdga_number'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('gt_number',), name='unique_gt_number'),
        ),
    ]
