# Generated by Django 2.2.17 on 2021-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0034_auto_20210317_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='tremonia_series_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Tremonia Series Wins'),
        ),
    ]
