# Generated by Django 2.2.17 on 2021-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0035_friend_tremonia_series_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
