# Generated by Django 2.2.17 on 2021-11-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0036_tournament_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_url_for_tournament'),
        ),
    ]
