# Generated by Django 2.2.17 on 2021-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0037_auto_20211101_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='metrix_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disc Golf Metrix User ID'),
        ),
    ]
