# Generated by Django 2.2.17 on 2021-11-02 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0038_friend_metrix_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friend',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)],
                                                         verbose_name='Position')),
                ('friend',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dgf.Friend',
                                   verbose_name='Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results',
                                                 to='dgf.Tournament', verbose_name='Tournament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('tournament', 'friend', 'position'),
                                               name='the same tournament can not be played twice'),
        ),
    ]
