# Generated by Django 2.2.17 on 2021-11-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0040_auto_20211103_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='tremonia_series_wins',
        ),
    ]
