# Generated by Django 2.2.17 on 2021-11-05 08:30

import dgf.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0042_re_create_result_model'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friend',
            managers=[
                ('all_objects', django.contrib.auth.models.UserManager()),
                ('objects', dgf.models.OnlyFriendsManager()),
                ('non_friends', dgf.models.NonFriendsManager()),
            ],
        ),
    ]
