# Generated by Django 2.2.17 on 2021-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0046_auto_20211110_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='gt_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='GT Number'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='metrix_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disc Golf Metrix User ID'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='pdga_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PDGA Number'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='udisc_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UDisc Username'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='gt_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='GT ID'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='metrix_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Disc Golf Metrix ID'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pdga_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PDGA ID'),
        ),
    ]
