# Generated by Django 2.2.17 on 2021-11-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0047_auto_20211110_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
