# Generated by Django 2.2.17 on 2021-11-16 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0050_tourpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='tour',
            name='point_system',
            field=models.CharField(
                choices=[('ts_points_with_beaten_players', 'Tremonia Series points + half beaten players')],
                default='ts_points_with_beaten_players', max_length=100, verbose_name='Point System'),
        ),
    ]
