# Generated by Django 2.2.17 on 2021-11-16 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0050_tourpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='tour',
            name='point_system',
            field=models.CharField(default='TS_POINTS_PLUS_BEATEN_PLAYERS',
                                   help_text='Available point systems: TS_POINTS_PLUS_BEATEN_PLAYERS', max_length=300,
                                   verbose_name='Name'),
            preserve_default=False,
        ),
    ]
