# Generated by Django 2.2.17 on 2021-11-15 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0050_tourpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='points',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='point_system',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
    ]
