# Generated by Django 2.2.17 on 2021-11-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0051_auto_20211116_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='tournaments', to='dgf.Tour'),
        ),
    ]
