# Generated by Django 2.2.17 on 2021-11-15 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0052_tour_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='Points'),
        ),
    ]
