# Generated by Django 2.2.17 on 2021-11-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0052_auto_20211116_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='point_system',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='tournaments',
            field=models.ManyToManyField(related_name='tours', to='dgf.Tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='point_system',
            field=models.CharField(blank=True, choices=[
                ('ts_points_with_beaten_players', 'Tremonia Series points + half beaten players points')],
                                   max_length=100, null=True, verbose_name='Point System'),
        ),
    ]
