# Generated by Django 2.2.17 on 2021-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0053_auto_20211115_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='point_system',
            field=models.CharField(help_text='Available point systems: TS_POINTS_PLUS_BEATEN_PLAYERS', max_length=300,
                                   null=True, verbose_name='Name'),
        ),
    ]
