# Generated by Django 2.2.17 on 2021-11-25 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0053_auto_20211119_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='evaluate_how_many',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='How many tournaments should be evaluated?'),
        ),
    ]
