# Generated by Django 3.2.12 on 2022-03-14 20:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0054_tour_evaluate_how_many'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tournament',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
