# Generated by Django 3.2.12 on 2022-03-16 22:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0055_auto_20220314_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagtagChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)],
                                                           verbose_name='New number')),
                ('previous_number', models.PositiveIntegerField(blank=True, null=True, validators=[
                    django.core.validators.MinValueValidator(1)], verbose_name='Previous number')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='bagtag',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MaxValueValidator(100)],
                                              verbose_name='Bagtag'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('bagtag',), name='unique_bagtag'),
        ),
        migrations.AddField(
            model_name='bagtagchange',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagtag_changes',
                                    to='dgf.friend', verbose_name='Player'),
        ),
    ]
