# Generated by Django 3.2.12 on 2022-03-16 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0056_auto_20220316_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagtagchange',
            name='new_number',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)],
                                              verbose_name='New number'),
        ),
    ]
