# Generated by Django 3.2.12 on 2022-03-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0057_alter_bagtagchange_new_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagtagchange',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
