# Generated by Django 3.2.12 on 2022-03-17 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0058_alter_bagtagchange_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='bagtag',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MaxValueValidator(500)],
                                              verbose_name='Bagtag'),
        ),
    ]
