# Generated by Django 3.2.12 on 2022-03-17 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0059_alter_friend_bagtag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_bagtag',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='bagtag',
        ),
        migrations.AddField(
            model_name='friend',
            name='bag_tag',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MaxValueValidator(500)],
                                              verbose_name='Bag Tag'),
        ),
        migrations.AlterField(
            model_name='bagtagchange',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_tag_changes',
                                    to='dgf.friend', verbose_name='Player'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('bag_tag',), name='unique_bag_tag'),
        ),
    ]
