# Generated by Django 3.2.13 on 2022-04-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0063_alter_bagtagchange_new_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='unique_url_for_tournament',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='url',
        ),
    ]
