# Generated by Django 3.2.13 on 2022-04-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0065_result_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='division',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='dgf.division',
                                    verbose_name='Division'),
        ),
    ]
