# Generated by Django 3.2.13 on 2022-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0066_tour_division'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tour',
            name='unique tour name',
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(fields=('name', 'division'), name='unique tour name and division'),
        ),
    ]
