# Generated by Django 3.2.13 on 2022-06-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0069_alter_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentResultsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True,
                                                       related_name='dgf_tournamentresultspluginmodel',
                                                       serialize=False, to='cms.cmsplugin')),
                ('background_image', models.ImageField(upload_to='')),
                ('show_only_friends', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.tournament')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
