# Generated by Django 3.2.13 on 2022-05-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('djangocms_picture', '0011_auto_20190314_1536'),
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0069_alter_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscGolfMetrixResultPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True,
                                                       related_name='dgf_discgolfmetrixresultpluginmodel',
                                                       serialize=False, to='cms.cmsplugin')),
                ('url', models.CharField(max_length=100, verbose_name='Disc Golf Metrix URL')),
                ('background_image',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_picture.picture')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
