# Generated by Django 3.2.13 on 2022-06-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0070_tournamentresultspluginmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-end']},
        ),
        migrations.AddField(
            model_name='tournamentresultspluginmodel',
            name='height',
            field=models.TextField(default='500px'),
        ),
        migrations.AddField(
            model_name='tournamentresultspluginmodel',
            name='width',
            field=models.TextField(default='800px'),
        ),
    ]
