# Generated by Django 3.2.13 on 2022-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0070_discgolfmetrixresultpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discgolfmetrixresultpluginmodel',
            name='background_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='discgolfmetrixresultpluginmodel',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
