# Generated by Django 3.2.13 on 2022-06-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0071_auto_20220620_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentresultspluginmodel',
            name='height',
            field=models.CharField(default='500px', max_length=6),
        ),
        migrations.AlterField(
            model_name='tournamentresultspluginmodel',
            name='width',
            field=models.CharField(default='800px', max_length=6),
        ),
    ]
