# Generated by Django 3.2.13 on 2022-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0071_auto_20220523_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='discgolfmetrixresultpluginmodel',
            name='show_only_friends',
            field=models.BooleanField(default=True),
        ),
    ]
