# Generated by Django 3.2.13 on 2022-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0072_discgolfmetrixresultpluginmodel_show_only_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='discgolfmetrixresultpluginmodel',
            name='use_manually_combined_summary_table',
            field=models.BooleanField(default=False),
        ),
    ]
