# Generated by Django 3.2.13 on 2022-06-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0072_auto_20220620_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dgf_resultspluginmodel', serialize=False, to='cms.cmsplugin')),
                ('background_image', models.ImageField(upload_to='')),
                ('width', models.CharField(default='800px', max_length=6)),
                ('height', models.CharField(default='500px', max_length=6)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ConcreteTournamentResultsPluginModel',
            fields=[
                ('resultspluginmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dgf.resultspluginmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.tournament')),
            ],
            options={
                'abstract': False,
            },
            bases=('dgf.resultspluginmodel',),
        ),
        migrations.CreateModel(
            name='LastTremoniaSeriesResultsPluginModel',
            fields=[
                ('resultspluginmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dgf.resultspluginmodel')),
                ('show_only_friends', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('dgf.resultspluginmodel',),
        ),
        migrations.DeleteModel(
            name='TournamentResultsPluginModel',
        ),
    ]
