# Generated by Django 3.2.13 on 2022-06-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0073_discgolfmetrixresultpluginmodel_use_manually_combined_summary_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discgolfmetrixresultpluginmodel',
            name='use_manually_combined_summary_table',
        ),
        migrations.AddField(
            model_name='discgolfmetrixresultpluginmodel',
            name='table_type',
            field=models.CharField(choices=[('M', 'Use manually combined summary table'), ('D', 'Use default results table (containing results from 2 different courses)'), ('S', 'Use default results table (containing all results, from all the holes)')], default='S', max_length=1, verbose_name='Table type'),
        ),
    ]
