# Generated by Django 3.2.15 on 2022-09-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0073_auto_20220915_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='social_media_agreement',
            field=models.BooleanField(null=True),
        ),
    ]
