# Generated by Django 3.2.15 on 2022-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0074_friend_social_media_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='social_media_agreement',
            field=models.BooleanField(null=True,
                                      verbose_name='Can we use this profile information in our social media accounts?'),
        ),
    ]
