# Generated by Django 3.2.16 on 2022-11-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0075_alter_friend_social_media_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TremoniaSeriesHallOfFamePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dgf_tremoniaserieshalloffamepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('division', models.ForeignKey(limit_choices_to={'id__in': ['MPO', 'MA4']}, on_delete=django.db.models.deletion.CASCADE, to='dgf.division')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
