# Generated by Django 3.2.16 on 2022-11-19 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0076_tremoniaserieshalloffamepluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubissue',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
