# Generated by Django 3.2.20 on 2023-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0078_allow_2_different_results_for_the_same_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='point_system',
            field=models.CharField(blank=True, choices=[
                ('ts_points_with_beaten_players', 'Tremonia Series points + half beaten players'),
                ('keep_points_from_import', 'Tremonia Putting Liga points (0-200): keep points from import')],
                                   max_length=100, null=True, verbose_name='Point System'),
        ),
    ]
