# Generated by Django 3.2.20 on 2023-12-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0079_auto_20231127_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFamePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dgf_halloffamepluginmodel', serialize=False, to='cms.cmsplugin')),
                ('type', models.CharField(choices=[('ts', 'Tremonia Series'), ('tpl', 'Tremonia Putting Liga')], max_length=50)),
                ('division', models.ForeignKey(limit_choices_to={'id__in': ['MPO', 'MA4']}, on_delete=django.db.models.deletion.CASCADE, to='dgf.division')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
