# Generated by Django 3.2.20 on 2023-12-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0081_managementcommandexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcommandexecution',
            name='exception',
            field=models.CharField(max_length=50, null=True, verbose_name='Exception'),
        ),
        migrations.AddField(
            model_name='managementcommandexecution',
            name='exception_args',
            field=models.CharField(max_length=200, null=True, verbose_name='Exception args'),
        ),
    ]
