# Generated by Django 3.2.20 on 2023-12-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0082_auto_20231211_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcommandexecution',
            name='exception_args',
        ),
        migrations.AlterField(
            model_name='managementcommandexecution',
            name='exception',
            field=models.CharField(max_length=500, null=True, verbose_name='Exception'),
        ),
    ]
