# Generated by Django 3.2.20 on 2023-12-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0083_auto_20231211_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TremoniaSeriesHallOfFamePluginModel',
        ),
    ]
