# Generated by Django 3.2.23 on 2024-02-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0084_delete_tremoniaserieshalloffamepluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sponsor_link',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sponsor_logo',
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='dgf.friend', verbose_name='Friend')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(fields=('friend', 'name'), name='each sponsor can only be assigned once to the friend'),
        ),
    ]
