# Generated by Django 3.2.24 on 2024-03-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0084_delete_tremoniaserieshalloffamepluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='total_tournaments',
        ),
    ]
