# Generated by Django 3.2.23 on 2024-02-22 16:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_sponsor(apps, schema_editor):
    Friend = apps.get_model('dgf', 'Friend')
    Sponsor = apps.get_model('dgf', 'Sponsor')
    for friend in Friend.objects.all():
        if friend.sponsor:
            Sponsor.objects.create(friend=friend, name=friend.sponsor, link=friend.sponsor_link, logo=friend.sponsor_logo)


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0085_auto_20240306_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=False, max_length=200, null=False, verbose_name='name')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors',
                                             to='dgf.friend', verbose_name='Friend')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(fields=('friend', 'name'),
                                               name='each sponsor can only be assigned once to the friend'),
        ),
        migrations.RunPython(migrate_sponsor),
        migrations.RemoveField(
            model_name='friend',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sponsor_link',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='sponsor_logo',
        ),
    ]
