# Generated by Django 3.2.25 on 2025-05-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0085_auto_20240306_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConcreteTournamentResultsPluginModel',
        ),
        migrations.DeleteModel(
            name='LastTremoniaSeriesResultsPluginModel',
        ),
        migrations.DeleteModel(
            name='ResultsPluginModel',
        ),
    ]
