# Generated by Django 3.2.25 on 2024-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0086_sponsors_20240222_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='rank'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(fields=('friend', 'rank'), name='2 sponsors can not have the same rank'),
        ),
    ]
