# Generated by Django 3.2.25 on 2024-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0087_auto_20240923_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rank'),
        ),
    ]
