# Generated by Django 3.2.16 on 2023-01-20 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf_league', '0003_auto_20230114_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='points1',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
                verbose_name='Points Team 1'),
        ),
        migrations.AlterField(
            model_name='result',
            name='points2',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)],
                verbose_name='Points Team 2'),
        ),
    ]
