# Generated by Django 3.2.16 on 2023-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf_league', '0005_result_teams_only_play_once_against_each_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
