# Generated by Django 3.2.16 on 2023-01-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0078_allow_2_different_results_for_the_same_tournament'),
        ('dgf_league', '0006_auto_20230125_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendWithoutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searching',
                                             to='dgf.friend', verbose_name='Friend')),
            ],
        ),
    ]
