# Generated by Django 3.2.16 on 2023-01-21 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf_league', '0007_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                   django.core.validators.MaxValueValidator(10)],
                                                       verbose_name='Points')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results',
                                            to='dgf_league.match', verbose_name='Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results',
                                           to='dgf_league.team', verbose_name='Team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='teams_can_not_play_against_themselves'),
        ),
    ]
