# Generated by Django 3.2.16 on 2023-01-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf_league', '0007_friendwithoutteam'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendwithoutteam',
            constraint=models.UniqueConstraint(fields=('friend',), name='friend_can_only_search_for_team_once'),
        ),
    ]
