# Generated by Django 3.2.16 on 2023-01-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf_league', '0008_friendwithoutteam_friend_can_only_search_for_team_once'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendwithoutteam',
            options={'verbose_name_plural': 'Friends without team'},
        ),
    ]
