# Generated by Django 3.2.16 on 2023-01-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf_league', '0008_auto_20230121_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
