# Generated by Django 3.2.20 on 2023-12-21 07:48

from django.db import migrations, models
import django.utils.timezone


def fill_created_date(apps, schema_editor):
    Match = apps.get_model('dgf_league', 'Match')
    for match in Match.objects.all():
        match.created = match.date
        match.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dgf_league', '0009_alter_friendwithoutteam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(fill_created_date),
    ]
