# Generated by Django 3.2.20 on 2023-12-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf_league', '0010_match_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
    ]
