# Generated by Django 3.2.23 on 2024-01-17 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0084_delete_tremoniaserieshalloffamepluginmodel'),
        ('dgf_league', '0011_remove_team_unique_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembershipTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships_tpm',
                                   to='dgf.friend', verbose_name='Friend')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_tmp',
                                           to='dgf_league.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='ResultTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                   django.core.validators.MaxValueValidator(10)],
                                                       verbose_name='Points')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_tmp',
                                            to='dgf_league.match', verbose_name='Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_tmp',
                                           to='dgf_league.team', verbose_name='Team')),
            ],
        ),
    ]
