# Generated by Django 3.2.23 on 2024-01-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0084_delete_tremoniaserieshalloffamepluginmodel'),
        ('dgf_league', '0014_delete_teammembership_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultTmp',
            new_name='Result',
        ),
        migrations.RenameModel(
            old_name='TeamMembershipTmp',
            new_name='TeamMembership',
        ),
    ]
