# Generated by Django 3.2.23 on 2024-01-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0084_delete_tremoniaserieshalloffamepluginmodel'),
        ('dgf_league', '0015_rename_teammembershiptmp_resulttmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results',
                                    to='dgf_league.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='result',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results',
                                    to='dgf_league.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships',
                                    to='dgf.friend', verbose_name='Friend'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members',
                                    to='dgf_league.team', verbose_name='Team'),
        ),
    ]
