#!/bin/bash
# Production environment variables

export DJANGO_ENV="prod"
export DJANGO_SECRET_KEY="delete-me-and-take-this-from-a-file"
export DJANGO_DEBUG="False"
export DJANGO_ALLOWED_HOSTS="vps793990.ovh.net"
