# Generated by Django 2.2.10 on 2020-02-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('dgf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dgf_friendpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Friend')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
