# Generated by Django 2.2.10 on 2020-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0002_friendpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='friend',
            name='pdga_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
