# Generated by Django 2.2.11 on 2020-03-29 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0002_friend_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
