# Generated by Django 2.2.11 on 2020-04-05 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0003_auto_20200329_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100),
        ),
        migrations.AddField(
            model_name='friend',
            name='total_tournaments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
