# Generated by Django 2.2.11 on 2020-04-07 11:19

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0003_auto_20200329_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='friend',
            name='total_tournaments',
            field=models.IntegerField(blank=True, default=0, null=True,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
