# Generated by Django 2.2.11 on 2020-04-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0005_disc'),
        ('dgf', '0005_auto_20200410_2322'),
    ]

    operations = [
    ]
