# Generated by Django 2.2.11 on 2020-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0005_auto_20200410_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('mold', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
