# Generated by Django 2.2.11 on 2020-04-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf', '0007_auto_20200417_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscInBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('P', 'Putter'), ('M', 'Mid-range'), ('F', 'Fairway driver'), ('D', 'Distance driver')],
                    max_length=1)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgf.Disc')),
                ('friend',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discs', to='dgf.Friend')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discinbag',
            constraint=models.UniqueConstraint(fields=('disc', 'friend'), name='unique_disc_for_friend'),
        ),
    ]
