# Generated by Django 2.2.11 on 2020-04-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0016_feedback_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='club_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
