# Generated by Django 2.2.11 on 2020-05-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgf', '0020_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='favorite_course',
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='dgf.Course', verbose_name='Course')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to='dgf.Friend', verbose_name='Friend')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favoritecourse',
            constraint=models.UniqueConstraint(fields=('course', 'friend'), name='the same course can not be favorite twice'),
        ),
    ]
