# Generated by Django 3.2.16 on 2022-11-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(max_length=50, verbose_name='Slug')),
            ],
        ),
        migrations.AddConstraint(
            model_name='imagegenerator',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_image_generator_slug'),
        ),
    ]
