# Generated by Django 3.2.16 on 2022-11-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgf_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegenerator',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
