# Generated by Django 3.2.16 on 2022-11-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dgf_images', '0002_imagegenerator_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegenerator',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='imagegenerator',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
