# Generated by Django 3.2.16 on 2022-11-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgf_images', '0004_create_first_image_generator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageGenerator',
        ),
    ]
