from scripts.update_friend_fields import update_friend_fields

fields = ['social_media_agreement']
friends = {
    'alex': [True],
    'angela': [True],
    'antonia': [False],
    'armin': [True],
    'babara': [True],
    'basti': [True],
    'bettina': [False],
    'bjoern': [None],
    'chris': [None],
    'conni': [False],
    'david': [True],
    'davidb': [True],
    'dorina': [False],
    'fede': [True],
    'frank': [None],
    'helge': [None],
    'hilde': [None],
    'ilija': [True],
    'jan': [True],
    'jens': [True],
    'jesko': [True],
    'jogi': [None],
    'julia': [True],
    'julia-sophie': [False],
    'justus': [None],
    'jutta': [True],
    'kevin': [True],
    'kevind': [True],
    'lennard': [True],
    'louis': [False],
    'lux': [None],
    'manolo': [True],
    'marcel': [True],
    'marcelk': [True],
    'marcelr': [None],
    'marian': [True],
    'mario': [None],
    'markus': [True],
    'markuss': [None],
    'matthias': [True],
    'michael': [True],
    'nikola': [False],
    'oma': [False],
    'paul': [None],
    'ralf': [False],
    'ralfw': [None],
    'rene': [True],
    'ronnie': [True],
    'simon': [None],
    'simone': [True],
    'stefanie': [False],
    'stephan': [False],
    'sven': [None],
    'tana': [None],
    'tobias': [False],
    'uli': [None],
    'uwe': [False],
    'wolfgang': [False],
    'zinnia': [False],
}

update_friend_fields(fields, friends)
