# Generated by Django 3.2.12 on 2022-04-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cookie_consent', '0002_auto__add_logitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32, verbose_name='Language')),
                ('description', models.TextField(verbose_name='Description')),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_consent.cookie')),
            ],
        ),
        migrations.CreateModel(
            name='CookieGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('cookie_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie_consent.cookiegroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cookietranslation',
            constraint=models.UniqueConstraint(fields=('cookie', 'language'), name='unique_cookie_translation'),
        ),
        migrations.AddConstraint(
            model_name='cookiegrouptranslation',
            constraint=models.UniqueConstraint(fields=('cookie_group', 'language'),
                                               name='unique_cookie_group_translation'),
        ),
    ]
