#!/bin/bash
# Production environment variables

ROOT_INSTALLATION_PATH=/home/ubuntu

export DJANGO_ENV="prod"
export DJANGO_LOG_LEVEL="INFO"
export DJANGO_ALLOWED_HOSTS="discgolffriends.de,www.discgolffriends.de"
source ${ROOT_INSTALLATION_PATH}/secrets
export DJANGO_DGF_VERSION="$(cat ${ROOT_INSTALLATION_PATH}/django_project/ci/version)"
