from dgf.german_tour.attendance import update_all_tournaments_attendance, update_tournament_attendance
from dgf.german_tour.results import update_tournament_results, update_all_tournaments_results

# public functions

update_all_tournaments_attendance = update_all_tournaments_attendance
update_tournament_attendance = update_tournament_attendance

update_all_tournaments_results = update_all_tournaments_results
update_tournament_results = update_tournament_results
